[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc = '0.8.20'
evm_version = 'london'
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts']
ffi = true



# See more config options https://github.com/foundry-rs/foundry/tree/master/config
